-- ============================================================================
-- USER & PERMISSIONS — BATCH 4: تسجيل "كشوفات التوالف" + جداولها + إنفاذ فعلي
-- ============================================================================
-- هذا الملف SQL جاهز للتشغيل اليدوي على Supabase SQL Editor فقط.
-- لم يُشغَّل من قبل Claude — لا يوجد اتصال مباشر بقاعدة البيانات بهذه الجلسة.
-- شاشة جديدة كلياً (لا مستخدمين فعليين عليها اليوم) — نُفّذت أصلاً بمشروع منفصل
-- (Node/Express + PostgreSQL على Railway) وهذا الملف ينقلها لبنية الكيلاني
-- الموحّدة على Supabase، بجداول جديدة بالكامل ولا يعدّل أي جدول موجود مسبقاً.
-- يستبدل ملف "damage-schema.sql" الأصلي (سياسات RLS فيه كانت placeholder عامة
-- auth.role()='authenticated' — هذا الملف يشدّدها لتُقرأ من مصفوفة الصلاحيات).
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1) تسجيل الشاشة بجدول screens (Batch 1) — تظهر كعمود جديد بمصفوفة الصلاحيات
-- ----------------------------------------------------------------------------
insert into public.screens (id, name, file, status, screen_type) values
  ('damage-reports', 'كشوفات التوالف', 'شاشة_كشوفات_التوالف.html', 'active', 'business')
on conflict (id) do nothing;


-- ----------------------------------------------------------------------------
-- 2) جداول البيانات (جديدة بالكامل — نفس تصميم damage-schema.sql الأصلي)
-- ----------------------------------------------------------------------------
create table if not exists public.item_master(
  item_code text primary key,
  item_name text,
  uom text,
  unit_weight numeric not null default 0,
  unit_cost numeric not null default 0,
  storage text,
  tax_pct numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.damage_batches(
  id bigint generated by default as identity primary key,
  batch_date date not null default current_date,
  transfer_doc_num text,
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.damage_items(
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.damage_batches(id) on delete cascade,
  line_no int not null,
  item_code text not null,
  item_name text,
  qty numeric not null,
  uom text,
  unit_weight numeric not null default 0,
  unit_cost numeric not null default 0,
  tax_pct numeric not null default 0,
  storage text
);
create index if not exists idx_damage_items_batch on public.damage_items(batch_id);


-- ----------------------------------------------------------------------------
-- 3) RLS — إنفاذ فعلي عبر مصفوفة الصلاحيات (screen_id='damage-reports')، لا
--    سياسة عامة "أي مستخدم مسجّل دخول". يحذف أولاً سياسات placeholder القديمة
--    (لو كان damage-schema.sql الأصلي شُغّل سابقاً بالخطأ) قبل إنشاء الجديدة.
-- ----------------------------------------------------------------------------
alter table public.item_master enable row level security;
alter table public.damage_batches enable row level security;
alter table public.damage_items enable row level security;

drop policy if exists "authenticated read/write item_master" on public.item_master;
drop policy if exists "authenticated read/write damage_batches" on public.damage_batches;
drop policy if exists "authenticated read/write damage_items" on public.damage_items;

-- قراءة: أي مستوى صلاحية فعلي (VIEW/INPUT/ADMIN) على شاشة كشوفات التوالف، أو مدير صلاحيات
create policy dmg_im_select on public.item_master
  for select using (
    public.is_permissions_admin()
    or exists (select 1 from public.user_screen_permissions u
               where u.user_id = auth.uid() and u.screen_id = 'damage-reports')
  );
create policy dmg_batches_select on public.damage_batches
  for select using (
    public.is_permissions_admin()
    or exists (select 1 from public.user_screen_permissions u
               where u.user_id = auth.uid() and u.screen_id = 'damage-reports')
  );
create policy dmg_items_select on public.damage_items
  for select using (
    public.is_permissions_admin()
    or exists (select 1 from public.user_screen_permissions u
               where u.user_id = auth.uid() and u.screen_id = 'damage-reports')
  );

-- كتابة (إضافة/تعديل/حذف): فقط INPUT أو ADMIN على شاشة كشوفات التوالف، أو مدير صلاحيات
create policy dmg_im_write on public.item_master
  for all using (
    public.is_permissions_admin()
    or exists (select 1 from public.user_screen_permissions u
               where u.user_id = auth.uid() and u.screen_id = 'damage-reports' and u.permission in ('INPUT','ADMIN'))
  ) with check (
    public.is_permissions_admin()
    or exists (select 1 from public.user_screen_permissions u
               where u.user_id = auth.uid() and u.screen_id = 'damage-reports' and u.permission in ('INPUT','ADMIN'))
  );
create policy dmg_batches_write on public.damage_batches
  for all using (
    public.is_permissions_admin()
    or exists (select 1 from public.user_screen_permissions u
               where u.user_id = auth.uid() and u.screen_id = 'damage-reports' and u.permission in ('INPUT','ADMIN'))
  ) with check (
    public.is_permissions_admin()
    or exists (select 1 from public.user_screen_permissions u
               where u.user_id = auth.uid() and u.screen_id = 'damage-reports' and u.permission in ('INPUT','ADMIN'))
  );
create policy dmg_items_write on public.damage_items
  for all using (
    public.is_permissions_admin()
    or exists (select 1 from public.user_screen_permissions u
               where u.user_id = auth.uid() and u.screen_id = 'damage-reports' and u.permission in ('INPUT','ADMIN'))
  ) with check (
    public.is_permissions_admin()
    or exists (select 1 from public.user_screen_permissions u
               where u.user_id = auth.uid() and u.screen_id = 'damage-reports' and u.permission in ('INPUT','ADMIN'))
  );

-- ملاحظة: السياسة أعلاه على مستوى select تكفّي أيضاً للكتابة (for all يشمل select)،
-- لكن نُبقي dmg_*_select منفصلة صراحةً حتى تعمل مطالعة VIEW-only حتى لو تغيّرت شروط
-- الكتابة لاحقاً — PostgreSQL يجمع سياسات الأمر نفسه بـ OR فتبقى القراءة مفتوحة لـVIEW.


-- ============================================================================
-- ⚠️ خطوة إلزامية قبل فتح الشاشة لأي موظف:
-- ============================================================================
-- بما إنها شاشة جديدة كلياً، افتح شاشة "إدارة المستخدمين والصلاحيات" وعيّن صلاحية
-- صريحة (VIEW/INPUT/ADMIN) على عمود "كشوفات التوالف" لكل موظف كان يستخدم النظام
-- القديم على Railway، قبل ما تشارك رابط الشاشة الجديدة معهم — بدون صف = NONE = ممنوع
-- الدخول كلياً (لا استثناء "allowed_apps" هنا، هذه الشاشة الوحيد الذي يحكمها هو
-- user_screen_permissions).
--
-- ترحيل البيانات التاريخية من قاعدة Railway القديمة (item_master/damage_batches/
-- damage_items) لهذه الجداول الجديدة خطوة منفصلة لم تُنفَّذ بعد — ليست جزءاً من
-- هذا الملف.
-- ============================================================================
